In [1]:
print ("Hello World")
a=92
print (a)

Hello World
92


In [8]:
a=(1,2,3,4,5,6,7)
a

(1, 2, 3, 4, 5, 6, 7)

In [9]:
b=(7,8,9)
c=a+b
c


(1, 2, 3, 4, 5, 6, 7, 7, 8, 9)

In [6]:
import numpy as np
print (np.version.version)

1.19.2


In [31]:
A=np.array([[1,2,3,4], [5,6,7,8]])
print (A)
print (A.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [30]:
B=np.array([[5,6,7,8],[9,10,11,12]],)
print (B.ndim)
B

2


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
D=np.linalg.inv(B)
D

array([[-2.5 ,  1.5 ],
       [ 2.25, -1.25]])

In [26]:
E=np.linalg.inv(D)
E

array([[ 5.,  6.],
       [ 9., 10.]])

In [28]:
F=np.sqrt(A)
F

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [32]:
G=A*B
G

array([[ 5, 12, 21, 32],
       [45, 60, 77, 96]])

In [34]:
import pandas as pd


In [35]:
import urllib


In [36]:
import os

In [ ]:
Datafile=pd.read_csv(filename)